// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-ordenes.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_ordenes_default = defineTool({
  name: "list_ordenes",
  title: "Listar \xF3rdenes de pago",
  description: "Lista \xF3rdenes de pago visibles para el usuario autenticado (respeta RLS, rol y scope por departamento). Filtros opcionales por status, departamento y l\xEDmite.",
  inputSchema: {
    status: z.enum([
      "borrador",
      "en_revision",
      "vobo_dado",
      "aprobada",
      "rechazada",
      "devuelta",
      "revocada",
      "pagada"
    ]).optional().describe("Filtrar por estatus de la orden."),
    departamento: z.string().optional().describe("Filtrar por departamento."),
    limit: z.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, departamento, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    let q = supabaseForUser(ctx).from("ordenes_pago").select(
      "id, folio, concepto, proveedor_nombre, monto, moneda, status, prioridad, departamento, categoria_gasto, fecha_pago_requerida, created_at"
    ).order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    if (departamento) q = q.eq("departamento", departamento);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { ordenes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-orden.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_orden_default = defineTool2({
  name: "get_orden",
  title: "Obtener orden de pago",
  description: "Obtiene el detalle completo de una orden de pago por su ID (UUID).",
  inputSchema: {
    id: z2.string().uuid().describe("UUID de la orden de pago.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const { data, error } = await supabaseForUser2(ctx).from("ordenes_pago").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No encontrada" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { orden: data }
    };
  }
});

// src/lib/mcp/tools/create-orden.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_orden_default = defineTool3({
  name: "create_orden",
  title: "Crear orden de pago",
  description: "Crea una nueva orden de pago (borrador o enviada a revisi\xF3n). Requiere rol capturista o admin. El solicitante es el usuario autenticado.",
  inputSchema: {
    empresa_id: z3.string().uuid().describe("UUID de la empresa."),
    concepto: z3.string().min(3),
    proveedor_nombre: z3.string().min(1),
    proveedor_rfc: z3.string().optional(),
    monto: z3.number().positive(),
    moneda: z3.string().default("MXN"),
    departamento: z3.string().min(1),
    categoria_gasto: z3.string().min(1),
    centro_costo: z3.string().optional(),
    prioridad: z3.enum(["baja", "media", "alta", "urgente"]).default("media"),
    fecha_pago_requerida: z3.string().optional().describe("Formato YYYY-MM-DD."),
    notas: z3.string().optional(),
    enviar_a_revision: z3.boolean().default(false).describe("Si true, la orden se env\xEDa directamente a revisi\xF3n; si no, queda como borrador.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const { enviar_a_revision, ...rest } = input;
    const { data, error } = await supabaseForUser3(ctx).from("ordenes_pago").insert({
      ...rest,
      solicitante_id: ctx.getUserId(),
      status: enviar_a_revision ? "en_revision" : "borrador"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Orden creada folio #${data.folio}` }],
      structuredContent: { orden: data }
    };
  }
});

// src/lib/mcp/tools/orden-accion.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var orden_accion_default = defineTool4({
  name: "orden_accion",
  title: "Ejecutar acci\xF3n sobre orden",
  description: "Ejecuta una acci\xF3n de flujo sobre una orden: aprobar, rechazar, devolver, revocar (solo autorizador), vobo (verificador/contador) o confirmar. La l\xF3gica de permisos y umbrales se valida en el backend seg\xFAn el rol del usuario.",
  inputSchema: {
    orden_id: z4.string().uuid(),
    accion: z4.enum(["aprobar", "rechazar", "devolver", "revocar", "vobo", "confirmar"]),
    comentario: z4.string().optional().describe("Comentario o motivo (obligatorio para rechazar/devolver).")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ orden_id, accion, comentario }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const url = `${process.env.SUPABASE_URL}/functions/v1/orden-accion`;
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${ctx.getToken()}`,
        apikey: process.env.SUPABASE_PUBLISHABLE_KEY
      },
      body: JSON.stringify({ orden_id, accion, comentario })
    });
    const text = await res.text();
    if (!res.ok)
      return { content: [{ type: "text", text: `Error ${res.status}: ${text}` }], isError: true };
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/tools/dashboard-summary.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var dashboard_summary_default = defineTool5({
  name: "dashboard_summary",
  title: "Resumen del dashboard",
  description: "Devuelve conteos por estatus y montos totales de las \xF3rdenes visibles para el usuario autenticado (respeta RLS y scope por departamento).",
  inputSchema: {
    dias: z5.number().int().min(1).max(365).default(30).describe("Ventana en d\xEDas hacia atr\xE1s.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ dias }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const desde = new Date(Date.now() - dias * 864e5).toISOString();
    const { data, error } = await supabaseForUser4(ctx).from("ordenes_pago").select("status, monto, moneda, departamento").gte("created_at", desde);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const porStatus = {};
    const porDepto = {};
    for (const r of data ?? []) {
      const s = r.status;
      porStatus[s] ??= { count: 0, monto: 0 };
      porStatus[s].count++;
      porStatus[s].monto += Number(r.monto ?? 0);
      const d = r.departamento;
      porDepto[d] ??= { count: 0, monto: 0 };
      porDepto[d].count++;
      porDepto[d].monto += Number(r.monto ?? 0);
    }
    const summary = { dias, total: data?.length ?? 0, por_status: porStatus, por_departamento: porDepto };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wgkzvozzdslbasntjhbb";
var mcp_default = defineMcp({
  name: "daiki-autorizaciones-mcp",
  title: "Daiki \xB7 Autorizaciones",
  version: "0.1.0",
  instructions: "Herramientas para el sistema Daiki de autorizaciones de pago (Grupo Zabia). Permite listar y consultar \xF3rdenes de pago, crear nuevas \xF3rdenes (rol capturista/admin) y ejecutar acciones de flujo (aprobar, rechazar, devolver, VoBo, revocar) seg\xFAn el rol del usuario autenticado. Todas las operaciones respetan RLS y el scope por departamento.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_ordenes_default, get_orden_default, create_orden_default, orden_accion_default, dashboard_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
